### ISSUE TITLE
Not working in Firefox 44.0

### ISSUE THREAD

**Issue by defkev** [ncalexan/fxa-custom-server-addon#7]
Installs just fine but tapping the "Custom Firefox Account" no longer displays the prompt, making it impossible to add a custom account.

The toast notifying about an existing account still works, so i suppose the problem is somewhere in

`function showPrefsPrompt(aWindow)`

Working in 43.0

**Comment by ncalexan** [comment]
Hi @defkev -- I've noted that this is deprecated as of Firefox 44, and linked to the (soon to be updated) documentation that should work for you.  (That documentation is in review, see https://github.com/mozilla-services/docs/pull/58.)

I'm not clear on why this would stop working for 43 -- perhaps a Firefox for Android API changed and I missed it.  Since the approach has changed and the addon is deprecated, I'm not going to address it.  Feel free to contact me directly about issues with custom accounts, though!

**Comment by defkev** [comment]
Nice to know!
Just updated my entire backend and noticed this.

One heads-up:
You forgot to mention the mandatory change to:

`identity.sync.tokenserver.uri`

in the draft.

Which needs to point to your syncserver (handling /token & /storage) otherwise you end up trying to sync to Mozillas servers will being authenticated to your own.

Cheers
